In [1]:
import pandas as pd

### correlated_MEDS_data

In [2]:
cmd_held_out0 = pd.read_parquet("example_data/correlated_MEDS_data/held_out/0.parquet")
cmd_held_out0

       subject_id                time                    code  numeric_value
0            9000 2009-09-19 00:00:00                     DOB            NaN
1            9000 2009-09-25 23:27:56               ADMISSION            NaN
2            9000 2009-10-30 00:58:53                    M199            NaN
3            9000 2010-04-23 06:07:40                    LAB4          106.0
4            9000 2010-05-26 10:24:25                    M254            NaN
...           ...                 ...                     ...            ...
39168        9499 2023-04-24 16:51:17                    M808            NaN
39169        9499 2024-11-17 10:06:51                    M486            NaN
39170        9499                 NaT             RACE//asian            NaN
39171        9499                 NaT  ETHNICITY//nonhispanic            NaN
39172        9499                 NaT               GENDER//F            NaN

[39173 rows x 4 columns]

In [3]:
cmd_held_out1 = pd.read_parquet("example_data/correlated_MEDS_data/held_out/1.parquet")
cmd_held_out1

       subject_id                time                 code  numeric_value
0            9500 1984-03-06 00:00:00                  DOB            NaN
1            9500 1984-11-10 06:29:13                 D722            NaN
2            9500 1984-11-16 02:27:44                 D233            NaN
3            9500 1985-07-11 13:44:37                 D459            NaN
4            9500 1985-07-21 03:23:25                 D177            NaN
...           ...                 ...                  ...            ...
40866        9999 2024-04-09 19:05:57                 M330            NaN
40867        9999 2025-11-07 13:10:34            DISCHARGE            NaN
40868        9999                 NaT          RACE//other            NaN
40869        9999                 NaT  ETHNICITY//hispanic            NaN
40870        9999                 NaT            GENDER//M            NaN

[40871 rows x 4 columns]

In [4]:
cmd_train0 = pd.read_parquet("example_data/correlated_MEDS_data/train/0.parquet")
cmd_train0

       subject_id                time                    code  numeric_value
0               0 2004-10-05 00:00:00                     DOB            NaN
1               0 2005-05-15 00:23:54                  LAB/GL           48.0
2               0 2005-05-15 00:23:54                    DE10            NaN
3               0 2005-05-15 00:23:54                    DE11            NaN
4               0 2005-05-15 00:23:54                   MME02            NaN
...           ...                 ...                     ...            ...
40723         499 2023-11-17 09:57:28               DISCHARGE            NaN
40724         499 2025-05-16 23:39:27               DISCHARGE            NaN
40725         499                 NaT             RACE//other            NaN
40726         499                 NaT  ETHNICITY//nonhispanic            NaN
40727         499                 NaT               GENDER//F            NaN

[40728 rows x 4 columns]

In [5]:
cmd_tuning0 = pd.read_parquet("example_data/correlated_MEDS_data/tuning/0.parquet")
cmd_tuning0

       subject_id                time                    code  numeric_value
0            8000 2003-02-26 00:00:00                     DOB            NaN
1            8000 2003-05-31 22:51:29               DISCHARGE            NaN
2            8000 2003-09-19 17:30:12                    M864            NaN
3            8000 2003-12-26 05:25:36                    LAB4          179.0
4            8000 2006-05-17 17:04:19                    DO60            NaN
...           ...                 ...                     ...            ...
41877        8499 2024-12-28 05:03:10                    M130            NaN
41878        8499 2025-04-22 23:06:57               DISCHARGE            NaN
41879        8499                 NaT             RACE//black            NaN
41880        8499                 NaT  ETHNICITY//nonhispanic            NaN
41881        8499                 NaT               GENDER//F            NaN

[41882 rows x 4 columns]

### example_MEDS_data

In [7]:
ex_held_out0 = pd.read_parquet("example_data/example_MEDS_data/held_out/0.parquet")
ex_held_out0

      subject_id                time                    code  numeric_value
0            450 1948-02-23 00:00:00                     DOB            NaN
1            450 1972-03-18 16:24:09                    D815            NaN
2            450 1990-12-04 22:04:43                    D752            NaN
3            450 1993-06-01 00:35:21               ADMISSION            NaN
4            450 1994-08-19 00:35:21               DISCHARGE            NaN
...          ...                 ...                     ...            ...
2321         499 2023-10-28 14:24:25                    M984            NaN
2322         499 2024-01-16 18:17:10               DISCHARGE            NaN
2323         499                 NaT             RACE//black            NaN
2324         499                 NaT  ETHNICITY//nonhispanic            NaN
2325         499                 NaT               GENDER//M            NaN

[2326 rows x 4 columns]

In [8]:
ex_train0 = pd.read_parquet("example_data/example_MEDS_data/train/0.parquet")
ex_train0

       subject_id                time                    code  numeric_value
0               0 2004-10-05 00:00:00                     DOB            NaN
1               0 2006-03-21 16:40:31                    D501            NaN
2               0 2006-03-24 06:48:23                    D685            NaN
3               0 2006-08-08 05:22:13                    D513            NaN
4               0 2006-10-22 12:52:29                     M78            NaN
...           ...                 ...                     ...            ...
14244         399 2024-12-23 14:46:44                    D515            NaN
14245         399 2025-05-12 14:21:45               DISCHARGE            NaN
14246         399                 NaT            RACE//native            NaN
14247         399                 NaT  ETHNICITY//nonhispanic            NaN
14248         399                 NaT               GENDER//F            NaN

[14249 rows x 4 columns]

In [9]:
ex_test0 = pd.read_parquet("example_data/example_MEDS_data/held_out/0.parquet")
ex_test0

      subject_id                time                    code  numeric_value
0            450 1948-02-23 00:00:00                     DOB            NaN
1            450 1972-03-18 16:24:09                    D815            NaN
2            450 1990-12-04 22:04:43                    D752            NaN
3            450 1993-06-01 00:35:21               ADMISSION            NaN
4            450 1994-08-19 00:35:21               DISCHARGE            NaN
...          ...                 ...                     ...            ...
2321         499 2023-10-28 14:24:25                    M984            NaN
2322         499 2024-01-16 18:17:10               DISCHARGE            NaN
2323         499                 NaT             RACE//black            NaN
2324         499                 NaT  ETHNICITY//nonhispanic            NaN
2325         499                 NaT               GENDER//M            NaN

[2326 rows x 4 columns]

### example_MEDS_data_wo_held_out

In [10]:
wo_train = pd.read_parquet("example_data/example_MEDS_data_wo_held_out/train/0.parquet")
wo_train

       subject_id                time                    code  numeric_value
0               0 2004-10-05 00:00:00                     DOB            NaN
1               0 2009-12-12 02:46:09                    LAB1          163.0
2               0 2010-03-03 04:24:43                    M105            NaN
3               0 2010-03-18 21:20:45                    D878            NaN
4               0 2012-09-09 18:19:50                    M379            NaN
...           ...                 ...                     ...            ...
25588         499 2024-11-27 03:16:23               ADMISSION            NaN
25589         499 2025-11-23 03:16:23               DISCHARGE            NaN
25590         499                 NaT             RACE//other            NaN
25591         499                 NaT  ETHNICITY//nonhispanic            NaN
25592         499                 NaT               GENDER//F            NaN

[25593 rows x 4 columns]

In [11]:
wo_test = pd.read_parquet("example_data/example_MEDS_data_wo_held_out/tuning/0.parquet")
wo_test

       subject_id                time                    code  numeric_value
0            8000 2003-02-26 00:00:00                     DOB            NaN
1            8000 2003-09-10 21:55:28                    LAB0          153.0
2            8000 2003-09-19 17:30:12                    M864            NaN
3            8000 2004-12-07 02:14:00                    LAB6          193.0
4            8000 2004-12-18 11:02:05                    LAB0          103.0
...           ...                 ...                     ...            ...
26011        8499 2024-11-27 05:53:53                    M856            NaN
26012        8499 2024-12-28 05:03:10                    M130            NaN
26013        8499                 NaT             RACE//black            NaN
26014        8499                 NaT  ETHNICITY//nonhispanic            NaN
26015        8499                 NaT               GENDER//F            NaN

[26016 rows x 4 columns]

### lab_correlated_MEDS_data

In [12]:
c_ho = pd.read_parquet("example_data/lab_correlated_MEDS_data/held_out/0.parquet")
c_ho

       subject_id                time                    code  numeric_value
0            9000 2009-09-19 00:00:00                     DOB            NaN
1            9000 2009-09-25 23:27:56               ADMISSION            NaN
2            9000 2009-10-30 00:58:53                    M199            NaN
3            9000 2010-04-23 06:07:40                    LAB4          106.0
4            9000 2010-05-26 10:24:25                    M254            NaN
...           ...                 ...                     ...            ...
24768        9499 2023-04-24 16:51:17                    M808            NaN
24769        9499 2024-11-17 10:06:51                    M486            NaN
24770        9499                 NaT             RACE//asian            NaN
24771        9499                 NaT  ETHNICITY//nonhispanic            NaN
24772        9499                 NaT               GENDER//F            NaN

[24773 rows x 4 columns]

In [13]:
c_train = pd.read_parquet("example_data/lab_correlated_MEDS_data/train/0.parquet")
c_train

       subject_id                time                    code  numeric_value
0               0 2004-10-05 00:00:00                     DOB            NaN
1               0 2010-03-03 04:24:43                    M105            NaN
2               0 2010-03-18 21:20:45                    D878            NaN
3               0 2012-09-09 18:19:50                    M379            NaN
4               0 2013-08-31 06:01:55                    LAB1          167.0
...           ...                 ...                     ...            ...
24701         499 2023-10-29 23:39:27               ADMISSION            NaN
24702         499 2025-05-16 23:39:27               DISCHARGE            NaN
24703         499                 NaT             RACE//other            NaN
24704         499                 NaT  ETHNICITY//nonhispanic            NaN
24705         499                 NaT               GENDER//F            NaN

[24706 rows x 4 columns]

In [14]:
c_test = pd.read_parquet("example_data/lab_correlated_MEDS_data/tuning/0.parquet")
c_test

       subject_id                time                    code  numeric_value
0            8000 2003-02-26 00:00:00                     DOB            NaN
1            8000 2003-05-31 22:51:29               DISCHARGE            NaN
2            8000 2003-09-19 17:30:12                    M864            NaN
3            8000 2003-12-26 05:25:36                    LAB4          179.0
4            8000 2006-12-18 02:53:07                    M139            NaN
...           ...                 ...                     ...            ...
26425        8499 2024-12-28 05:03:10                    M130            NaN
26426        8499 2025-04-22 23:06:57               DISCHARGE            NaN
26427        8499                 NaT             RACE//black            NaN
26428        8499                 NaT  ETHNICITY//nonhispanic            NaN
26429        8499                 NaT               GENDER//F            NaN

[26430 rows x 4 columns]